#!/usr/bin/env bash
source scripts/verify/common.sh
cd control-plane
run "Go formatting and syntax" bash -c 'out=$(gofmt -d ./cmd ./internal ./migrations 2>&1); test -z "$out" || { printf "%s\n" "$out"; exit 1; }'
run "Go build" go build ./...
run "Go vet" go vet ./...
run "Go unit and OpenAPI drift tests" env -u TEST_DATABASE_URL go test -p 1 ./...
