import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  METRICS,
  METRICS_MANIFEST_VERSION,
  estimatorLabel,
  metricInfo,
  metricTooltip,
  seriesInfo,
} from "./metricsManifest";

function findSource(rel: string): string {
  let dir = process.cwd();
  for (let i = 0; i < 6; i++) {
    const candidate = resolve(dir, rel);
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error(`${rel} not found from ${process.cwd()}`);
}

describe("metric manifest", () => {
  // The bundled copy is generated by `make docs-metrics-sync`. Byte equality is
  // also asserted Go-side; asserting it here too means a web-only run cannot
  // pass against a stale bundle.
  it("is byte-identical to docs/session-trace/metrics.json", () => {
    const source = readFileSync(findSource("docs/session-trace/metrics.json"), "utf8");
    const copy = readFileSync(findSource("web/src/lib/metrics.generated.json"), "utf8");
    expect(copy).toBe(source);
  });

  it("exposes a version and a non-trivial key set", () => {
    expect(METRICS_MANIFEST_VERSION).toMatch(/^\d{4}-\d{2}-\d{2}\.\d+$/);
    expect(METRICS.length).toBeGreaterThan(100);
  });

  // EVERY key buildMetrics() can post must be described. A posted key with no
  // manifest row is a number with no unit, clock, window or estimator anywhere
  // — the exact state this manifest exists to end. Read out of the source so
  // adding a key to buildMetrics without documenting it fails here.
  it("describes every key web/src/webrtc/telemetry.ts posts", () => {
    const src = readFileSync(findSource("web/src/webrtc/telemetry.ts"), "utf8");
    const build = src.slice(src.indexOf("private buildMetrics()"));
    const body = build.slice(0, build.indexOf("\n  }"));
    const posted = new Set<string>(
      [...body.matchAll(/m\["([a-z0-9_]+)"\]/g)].map((m) => m[1]),
    );
    // `fps` is set in the initializer, not through the m["..."] form, and
    // `is_hidden` is merged in by the caller.
    posted.add("fps");
    posted.add("is_hidden");
    expect(posted.size).toBeGreaterThan(20);

    const undocumented = [...posted].filter((k) => metricInfo(k) === undefined).sort();
    expect(undocumented).toEqual([]);
  });

  it("resolves by raw key and by taxonomy name, scoped by source", () => {
    // frames_dropped exists for BOTH sources with different meanings; the
    // lookup must not collapse them.
    expect(metricInfo("frames_dropped", "agent")?.taxonomy).toBe("encoder.frames_dropped");
    expect(metricInfo("frames_dropped", "browser")?.taxonomy).toBe("client.frames_dropped");
    expect(seriesInfo("client.present_interval_sd_ms")?.key).toBe("present_interval_sd_ms");
    expect(metricInfo("not-a-metric")).toBeUndefined();
  });

  it("labels the estimator and window a reader would otherwise have to know", () => {
    expect(estimatorLabel(metricInfo("decode_ms"))).toBe("mean 1 s");
    expect(estimatorLabel(metricInfo("glass_to_glass_ms"))).toBe("median rolling ≤600");
    expect(estimatorLabel(metricInfo("encode_ms", "agent"))).toBe("mean ~5 s");
    // An unknown key degrades to no qualifier rather than to a wrong one.
    expect(estimatorLabel(undefined)).toBe("");
    expect(metricTooltip(undefined)).toBe("");
  });

  it("names the replacement on a deprecated key's tooltip", () => {
    const tip = metricTooltip(metricInfo("glass_to_glass_ms"));
    expect(tip).toContain("DEPRECATED — read rvfc_capture_to_display_ms");
  });
});
