#!/bin/sh
# deploy/enroll-host.sh — join a machine to a Quasar control plane as a GPU host (#100).
#
#   curl -fsSL [-k --pinnedpubkey 'sha256//…'] https://<control-plane>/enroll-host.sh \
#     | QUASAR_ENROLLMENT='qenr1.…' QUASAR_REF=<ref> sh
#
# Admin → Fleet → Enroll host prints that line filled in. The control plane serves
# this file itself (the SPA build copies it into web/dist), so the script is by
# construction the one that matches the running deployment. With a self-signed
# control plane, curl trusts nothing but the pinned public key (`-k` alone would
# hand anyone on the path a root shell; `--pinnedpubkey` is what makes `-k`
# safe); with a real-CA certificate neither flag appears. The agent then pins the
# certificate fingerprint INSIDE the enrollment string (#12). The token travels in
# an environment variable, never a URL: it is single-use and expires in an hour,
# which is what makes a shell-history exposure bounded.
#
# What it does, in order (it prints each step; nothing is silent):
#   1. parses the string, refuses a ws:// (cleartext) control plane;
#   2. checks the host the way node-agent/src/readiness.rs will: Docker + Compose,
#      a DRM render node, /dev/uinput, unprivileged user namespaces (incl. the
#      Ubuntu 24.04+ AppArmor knob, #76), the NVIDIA container toolkit on NVIDIA;
#   3. pins the agent image to the release this script was fetched at;
#   4. writes $QUASAR_DIR/{docker-compose.yml,.env} — the .env is 0600 and is the
#      only place the enrollment string lands;
#   5. starts the one agent service (re-running updates it; never a second agent);
#   6. tails its log until it is enrolled, or names the failure.
# It never edits the firewall: media reachability is reported by the agent's own
# readiness check in Admin → Fleet, with the exact rule for this host.
#
# Inputs (environment):
#   QUASAR_ENROLLMENT   required — the string from Admin → Fleet → Enroll host
#   QUASAR_REF          the git ref the control plane was built from (vX.Y.Z tag,
#                       or a commit); it selects the matching agent image tag
#   QUASAR_AGENT_IMAGE  explicit image reference (a digest pin) — overrides QUASAR_REF
#   QUASAR_DIR          install directory, default /opt/quasar-agent
#   NODE_NAME           this host's stable fleet name, default: its hostname
#   QUASAR_HOME_ROOT    managed-home root, default /var/lib/quasar/homes
#   QUASAR_RENDER_NODE  render node to use, default: the detected one
#   QUASAR_ENROLL_DRY_RUN=1   print the plan; write and start nothing
#
# Sub-commands (argv): --print-compose, --print-nvidia-overlay, --help.
#
# The compose text below is the node-agent service from deploy/docker-compose.yml
# with the local-stack coupling removed (depends_on, CONTROL_PLANE_URL,
# ENROLLMENT_TOKEN) and QUASAR_ENROLLMENT added. control-plane's
# TestEnrollHostComposeMatchesBase fails the build if the two drift.
set -eu

IMAGE_REPO="ghcr.io/accreleus/quasar/quasar-node-agent"
LOCAL_IMAGE="quasar-node-agent:latest"
DIR="${QUASAR_DIR:-/opt/quasar-agent}"
ROOT="${QUASAR_ENROLL_ROOT:-}"          # test seam: fake /proc,/sys,/dev,/etc root
TAIL_SECS="${QUASAR_ENROLL_TAIL_SECS:-90}"
DRY="${QUASAR_ENROLL_DRY_RUN:-0}"
PROJECT="quasar-agent"

say() { printf '%s\n' "$*"; }
step() { printf '\n==> %s\n' "$*"; }
usage_error() { printf 'enroll-host: %s\n' "$*" >&2; exit 2; }
host_error() { printf 'enroll-host: %s\n' "$*" >&2; exit 1; }

# ── the compose text (kept in lockstep with deploy/docker-compose.yml) ───────
compose_yaml() {
cat <<'YAML'
# Generated by deploy/enroll-host.sh — the Quasar node-agent service alone.
# Mirrors the quasar-node-agent service in deploy/docker-compose.yml; edit the
# .env beside this file, not this file.
services:
  quasar-node-agent:
    image: ${QUASAR_AGENT_IMAGE:-${QUASAR_NODE_IMAGE:-quasar-node-agent:latest}}
    entrypoint: ["/usr/local/bin/quasar-node-agent-entrypoint"]
    network_mode: host
    cap_add: [NET_ADMIN, SYSLOG]
    init: true
    environment:
      QUASAR_ENROLLMENT: ${QUASAR_ENROLLMENT:?}
      NODE_NAME: ${NODE_NAME:-quasar-node-1}
      NODE_SECRET_PATH: /var/lib/quasar-agent/node-secret
      RUST_LOG: ${RUST_LOG:-info}
      XDG_RUNTIME_DIR: /run/quasar-agent
      QUASAR_ENCODER: ${QUASAR_ENCODER:-}
      QUASAR_RENDER_NODE: ${QUASAR_RENDER_NODE:-}
      QUASAR_HOME_ROOT: ${QUASAR_HOME_ROOT:-}
      QUASAR_HOMES_GC: ${QUASAR_HOMES_GC:-}
      QUASAR_HOMES_GC_RETENTION_HOURS: ${QUASAR_HOMES_GC_RETENTION_HOURS:-}
      QUASAR_HOMES_GC_DRY_RUN: ${QUASAR_HOMES_GC_DRY_RUN:-}
      QUASAR_HOME_TEMPLATES: ${QUASAR_HOME_TEMPLATES:-}
      QUASAR_TEMPLATE_WARMUP: ${QUASAR_TEMPLATE_WARMUP:-}
      QUASAR_TEMPLATE_ROOT: ${QUASAR_TEMPLATE_ROOT:-}
      QUASAR_TEMPLATE_CLONE_MODE: ${QUASAR_TEMPLATE_CLONE_MODE:-}
      QUASAR_TEMPLATE_ALLOW_CROSSFS: ${QUASAR_TEMPLATE_ALLOW_CROSSFS:-}
      QUASAR_TEMPLATE_SETTLE_SECS: ${QUASAR_TEMPLATE_SETTLE_SECS:-}
      QUASAR_TEMPLATE_WARMUP_TIMEOUT_SECS: ${QUASAR_TEMPLATE_WARMUP_TIMEOUT_SECS:-}
      QUASAR_TEMPLATE_MIN_FREE_BYTES: ${QUASAR_TEMPLATE_MIN_FREE_BYTES:-}
      QUASAR_ZEROCOPY: ${QUASAR_ZEROCOPY:-0}
      QUASAR_LATENCY_PROBE: ${QUASAR_LATENCY_PROBE:-0}
      QUASAR_CAPTURE_H264: ${QUASAR_CAPTURE_H264:-}
      LIBVA_TRACE: ${LIBVA_TRACE:-}
      GST_DEBUG: ${GST_DEBUG:-${VULKAN_GST_DEBUG:-}}
      QUASAR_TARGET_USAGE: ${QUASAR_TARGET_USAGE:-6}
      QUASAR_QUEUE_BUFFERS: ${QUASAR_QUEUE_BUFFERS:-3}
      QUASAR_SLICES: ${QUASAR_SLICES:-8}
      QUASAR_FEC_MODE: ${QUASAR_FEC_MODE:-}
      QUASAR_FEC_PERCENTAGE: ${QUASAR_FEC_PERCENTAGE:-0}
      QUASAR_FEC_ARM_LOSS_PCT: ${QUASAR_FEC_ARM_LOSS_PCT:-}
      QUASAR_FEC_WINDOW_S: ${QUASAR_FEC_WINDOW_S:-}
      QUASAR_FEC_ARM_WINDOWS: ${QUASAR_FEC_ARM_WINDOWS:-}
      QUASAR_FEC_DISARM_WINDOWS: ${QUASAR_FEC_DISARM_WINDOWS:-}
      QUASAR_FEC_MAX_FLAPS: ${QUASAR_FEC_MAX_FLAPS:-}
      QUASAR_INTRA_REFRESH: ${QUASAR_INTRA_REFRESH:-0}
      QUASAR_INTRA_REFRESH_PERIOD: ${QUASAR_INTRA_REFRESH_PERIOD:-0}
      QUASAR_VULKAN_H264: ${QUASAR_VULKAN_H264:-}
      QUASAR_VULKAN_HEVC: ${QUASAR_VULKAN_HEVC:-}
      QUASAR_VULKAN_AV1: ${QUASAR_VULKAN_AV1:-}
      WOLF_VULKAN_RING: ${WOLF_VULKAN_RING:-}
      QUASAR_TRACE_RTP_TS: ${QUASAR_TRACE_RTP_TS:-}
      QUASAR_TRACE_RTP_MARKER: ${QUASAR_TRACE_RTP_MARKER:-}
      QUASAR_TRACE_ENC_PTS: ${QUASAR_TRACE_ENC_PTS:-}
      QUASAR_ABR: ${QUASAR_ABR:-1}
      QUASAR_ABR_MODE: ${QUASAR_ABR_MODE:-smooth}
      QUASAR_ABR_FLOOR_KBPS: ${QUASAR_ABR_FLOOR_KBPS:-}
      QUASAR_ABR_FLOOR_RATIO: ${QUASAR_ABR_FLOOR_RATIO:-0.3}
      QUASAR_ABR_EWMA_ALPHA: ${QUASAR_ABR_EWMA_ALPHA:-}
      QUASAR_ABR_DEADBAND: ${QUASAR_ABR_DEADBAND:-}
      QUASAR_ABR_MAX_UP_STEP: ${QUASAR_ABR_MAX_UP_STEP:-}
      QUASAR_ABR_MIN_INTERVAL_MS: ${QUASAR_ABR_MIN_INTERVAL_MS:-}
      QUASAR_ABR_MAX_DOWN_STEP: ${QUASAR_ABR_MAX_DOWN_STEP:-}
      QUASAR_ABR_DOWN_DWELL_MS: ${QUASAR_ABR_DOWN_DWELL_MS:-}
      QUASAR_ABR_CLIFF_GUARD_FRAC: ${QUASAR_ABR_CLIFF_GUARD_FRAC:-}
      MALLOC_ARENA_MAX: ${MALLOC_ARENA_MAX:-}
      MALLOC_TRIM_THRESHOLD_: ${MALLOC_TRIM_THRESHOLD_:-}
      MALLOC_MMAP_THRESHOLD_: ${MALLOC_MMAP_THRESHOLD_:-}
      QUASAR_MALLOC_TRIM: ${QUASAR_MALLOC_TRIM:-}
      QUASAR_AUDIO_DISABLED: ${QUASAR_AUDIO_DISABLED:-}
      QUASAR_AUDIO_NO_CLOCK: ${QUASAR_AUDIO_NO_CLOCK:-}
      QUASAR_AUDIO_REQUIRED: ${QUASAR_AUDIO_REQUIRED:-}
      QUASAR_INPUT_TRACE: ${QUASAR_INPUT_TRACE:-}
      QUASAR_INPUT_CHANNEL_MODE: ${QUASAR_INPUT_CHANNEL_MODE:-}
      QUASAR_INPUT_BATCH_MS: ${QUASAR_INPUT_BATCH_MS:-}
      QUASAR_INPUT_CONTROLLER_NUDGE: ${QUASAR_INPUT_CONTROLLER_NUDGE:-}
      LIBGL_ALWAYS_SOFTWARE: ${LIBGL_ALWAYS_SOFTWARE-}
      MESA_LOADER_DRIVER_OVERRIDE: ${MESA_LOADER_DRIVER_OVERRIDE-}
      QUASAR_PULSE_IMAGE: ${QUASAR_PULSE_IMAGE:-${QUASAR_AGENT_IMAGE:-${QUASAR_NODE_IMAGE:-quasar-node-agent:latest}}}
      QUASAR_APP_SHM_SIZE: ${QUASAR_APP_SHM_SIZE:-1g}
      QUASAR_APP_STOP_TIMEOUT_SECS: ${QUASAR_APP_STOP_TIMEOUT_SECS:-10}
      QUASAR_CONTAINER_NETWORK: ${QUASAR_CONTAINER_NETWORK:-none}
      QUASAR_APP_PUID: ${QUASAR_APP_PUID:-}
      QUASAR_APP_PGID: ${QUASAR_APP_PGID:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/quasar-agent:/run/quasar-agent
      - /dev/input:/dev/input
      - ${QUASAR_HOME_ROOT:-/tmp/quasar-homes-unset}:${QUASAR_HOME_ROOT:-/tmp/quasar-homes-unset}
      - ${QUASAR_TEMPLATE_ROOT:-/var/lib/quasar/templates}:${QUASAR_TEMPLATE_ROOT:-/var/lib/quasar/templates}
      - /etc/os-release:/host/etc/os-release:ro
      - /dev:/host/dev:ro
      - quasar-agent-data:/var/lib/quasar-agent
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/kmsg:/dev/kmsg:r
    device_cgroup_rules:
      - 'c 13:* rmw'
    restart: unless-stopped
volumes:
  quasar-agent-data:
YAML
}

# The NVIDIA overlay, verbatim from deploy/docker-compose.nvidia.yml (comments
# stripped) — same drift test.
nvidia_yaml() {
cat <<'YAML'
# Generated by deploy/enroll-host.sh — NVIDIA overlay, from deploy/docker-compose.nvidia.yml.
services:
  quasar-node-agent:
    image: ${QUASAR_AGENT_IMAGE:-${QUASAR_NODE_IMAGE:-quasar-node-agent:latest}}
    gpus: all
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      QUASAR_PULSE_IMAGE: ${QUASAR_PULSE_IMAGE:-${QUASAR_AGENT_IMAGE:-${QUASAR_NODE_IMAGE:-quasar-node-agent:latest}}}
      QUASAR_GPU_NVIDIA: "1"
      QUASAR_CUDA_DEVICE: ${QUASAR_CUDA_DEVICE:-0}
      QUASAR_RENDER_NODE: ${QUASAR_RENDER_NODE:-/dev/dri/renderD128}
      QUASAR_NVIDIA_DRIVER_VOLUME: ${QUASAR_NVIDIA_DRIVER_VOLUME:-1}
      QUASAR_CUDA_RUNTIME: ${QUASAR_CUDA_RUNTIME:-1}
      LD_LIBRARY_PATH: /opt/quasar/nvidia-driver/lib64:/opt/quasar/nvidia-driver/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
      LIBVA_MESSAGING_LEVEL: "0"
    volumes:
      - quasar-nvidia-driver:/opt/quasar/nvidia-driver
volumes:
  quasar-nvidia-driver:
YAML
}

usage() {
  sed -n '2,40p' "$0" 2>/dev/null | sed 's/^# \{0,1\}//' || true
}

# ── sub-commands ─────────────────────────────────────────────────────────────
case "${1:-}" in
  --print-compose)        compose_yaml; exit 0 ;;
  --print-nvidia-overlay) nvidia_yaml; exit 0 ;;
  --help|-h)              usage; exit 0 ;;
  "") ;;
  *) usage_error "unknown argument '$1' (try --help)" ;;
esac

# ── 1. the enrollment string ─────────────────────────────────────────────────
blob="${QUASAR_ENROLLMENT:-}"
[ -n "$blob" ] || usage_error "QUASAR_ENROLLMENT is not set. Mint one in Admin → Fleet → Enroll host and run the command it prints:
  curl -fsSL … https://<control-plane>/enroll-host.sh | QUASAR_ENROLLMENT='qenr1.…' sh"

case "$blob" in
  qenr1.*) ;;
  *) usage_error "QUASAR_ENROLLMENT is not an enrollment string (expected it to start with 'qenr1.')" ;;
esac
rest="${blob#qenr1.}"
case "$rest" in *.*) ;; *) usage_error "QUASAR_ENROLLMENT is not an enrollment string (too few fields)" ;; esac
fp="${rest%%.*}"; rest="${rest#*.}"
case "$rest" in *.*) ;; *) usage_error "QUASAR_ENROLLMENT is not an enrollment string (too few fields)" ;; esac
url_b64="${rest%%.*}"; token="${rest#*.}"
[ -n "$url_b64" ] || usage_error "the enrollment string carries no control-plane address"
[ -n "$token" ] || usage_error "the enrollment string carries no token"
if [ -n "$fp" ] && ! printf '%s' "$fp" | grep -Eq '^([0-9A-F]{2}:){31}[0-9A-F]{2}$'; then
  usage_error "the enrollment string's fingerprint is not an uppercase colon-separated SHA-256 — was it pasted whole?"
fi

pad=$(( (4 - ${#url_b64} % 4) % 4 ))
padding=""
while [ "$pad" -gt 0 ]; do padding="$padding="; pad=$((pad - 1)); done
url="$(printf '%s%s' "$url_b64" "$padding" | tr -- '-_' '+/' | base64 -d 2>/dev/null)" ||
  usage_error "the control-plane address inside the enrollment string does not decode — was it pasted whole?"
case "$url" in
  wss://*) ;;
  ws://*) usage_error "the enrollment string points at $url — a cleartext ws:// control plane. The enrollment token and this host's node secret would cross the network unencrypted. Mint the string from the control plane's https:// page instead." ;;
  *) usage_error "the enrollment string's control-plane address is not a wss:// URL" ;;
esac
cp_host="${url#wss://}"; cp_host="${cp_host%%/*}"

step "Control plane"
say "  address:     $url"
if [ -n "$fp" ]; then
  say "  certificate: pinned to $fp"
  say "               (compare with the fingerprint= line in the control plane's startup log)"
else
  say "  certificate: public CA — verified normally, nothing pinned"
fi
say "  token:       single-use, read from QUASAR_ENROLLMENT (not shown)"

# ── privileges ───────────────────────────────────────────────────────────────
# Never prompt from inside a pipe: every privileged command runs `sudo -n`, and a
# host whose sudo wants a password is refused up front with the way out.
SUDO=""
if [ "$(id -u)" -ne 0 ]; then
  command -v sudo >/dev/null 2>&1 || host_error "not root and no sudo: this writes $DIR and talks to the Docker daemon. Run it from a root shell (su -, then paste the command)."
  if ! sudo -n true 2>/dev/null; then
    host_error "sudo asks $(id -un) for a password on this host, and this script never prompts. Either allow passwordless sudo for this user (NOPASSWD in sudoers), or open a root shell first (sudo -i) and paste the command there."
  fi
  SUDO="sudo -n"
fi

# ── 2. host preflights (the readiness checks, before anything is written) ────
step "Host preflights"

command -v docker >/dev/null 2>&1 || host_error "docker is not installed. Install Docker Engine first (https://docs.docker.com/engine/install/) — this script does not install it."
if [ "$DRY" != 1 ]; then
  $SUDO docker info >/dev/null 2>&1 || host_error "the Docker daemon is not reachable (is it running, and can $(id -un) use it?)"
fi
docker compose version >/dev/null 2>&1 || host_error "the Docker Compose v2 plugin is missing ('docker compose version' fails). Install docker-compose-plugin."
say "  docker + compose: ok"

distro=""
if [ -r "$ROOT/etc/os-release" ]; then
  distro="$(sed -n 's/^ID=//p' "$ROOT/etc/os-release" | tr -d '"')"
fi

# GPU: sysfs is the kernel's own view; the same source readiness.rs reads.
gpu=""; render_node=""
for vendor_file in "$ROOT"/sys/class/drm/renderD*/device/vendor; do
  [ -r "$vendor_file" ] || continue
  vendor="$(tr -d '[:space:]' < "$vendor_file")"
  node_dir="${vendor_file%/device/vendor}"
  candidate="/dev/dri/${node_dir##*/}"
  case "$vendor" in
    0x10de) gpu=nvidia; render_node="$candidate"; break ;;
    0x1002) [ -z "$gpu" ] && { gpu=amd; render_node="$candidate"; } ;;
    0x8086) [ -z "$gpu" ] && { gpu=intel; render_node="$candidate"; } ;;
  esac
done
[ -n "$gpu" ] || host_error "no DRM render node with a known GPU vendor under /sys/class/drm (renderD*). The agent needs a GPU with a loaded kernel driver; check 'ls /dev/dri' and the driver install."
say "  gpu: $gpu ($render_node)"

if [ "$gpu" = nvidia ]; then
  if ! command -v nvidia-ctk >/dev/null 2>&1 && ! command -v nvidia-container-cli >/dev/null 2>&1; then
    host_error "NVIDIA GPU, but the NVIDIA Container Toolkit is not installed (no nvidia-ctk / nvidia-container-cli). The agent's compose uses 'gpus: all'. Install it: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html"
  fi
  if [ ! -e "$ROOT/etc/cdi/nvidia.yaml" ] && [ ! -e "$ROOT/var/run/cdi/nvidia.yaml" ]; then
    say "  WARN: no CDI spec at /etc/cdi/nvidia.yaml — if the agent's readiness reports a CDI problem, generate one:"
    say "        sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml"
  fi
  say "  nvidia container toolkit: ok"
fi

[ -e "$ROOT/dev/uinput" ] || host_error "/dev/uinput is missing — virtual keyboard, mouse and gamepad injection cannot work. Load the module:
  sudo modprobe uinput && echo uinput | sudo tee /etc/modules-load.d/uinput.conf"
say "  /dev/uinput: ok"

# Unprivileged user namespaces, in the order readiness.rs decides them.
knob="$ROOT/proc/sys/kernel/unprivileged_userns_clone"
if [ -r "$knob" ] && [ "$(tr -d '[:space:]' < "$knob")" = 0 ]; then
  host_error "unprivileged user namespaces are disabled by kernel.unprivileged_userns_clone — sandboxed app launchers (bwrap, Steam's container runtime) cannot start. Fix, then re-run:
  sudo sysctl -w kernel.unprivileged_userns_clone=1 && echo kernel.unprivileged_userns_clone=1 | sudo tee /etc/sysctl.d/99-quasar-userns.conf"
fi
knob="$ROOT/proc/sys/kernel/apparmor_restrict_unprivileged_userns"
if [ -r "$knob" ] && [ "$(tr -d '[:space:]' < "$knob")" = 1 ]; then
  host_error "the host restricts unprivileged user namespaces through AppArmor (kernel.apparmor_restrict_unprivileged_userns=1, the Ubuntu 24.04+ default) — Steam's container runtime cannot start and every Steam-class app would exit before producing video (#76). Fix, then re-run:
  sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0 && echo kernel.apparmor_restrict_unprivileged_userns=0 | sudo tee /etc/sysctl.d/99-quasar-userns.conf"
fi
knob="$ROOT/proc/sys/user/max_user_namespaces"
if [ -r "$knob" ] && [ "$(tr -d '[:space:]' < "$knob")" = 0 ]; then
  case "$distro" in
    debian|ubuntu) hint="sudo sysctl -w user.max_user_namespaces=15000 kernel.unprivileged_userns_clone=1 && printf 'user.max_user_namespaces=15000\\nkernel.unprivileged_userns_clone=1\\n' | sudo tee /etc/sysctl.d/99-quasar-userns.conf" ;;
    *) hint="sudo sysctl -w user.max_user_namespaces=15000 && echo user.max_user_namespaces=15000 | sudo tee /etc/sysctl.d/99-quasar-userns.conf" ;;
  esac
  host_error "unprivileged user namespaces are disabled (user.max_user_namespaces=0) — sandboxed app launchers cannot start. Fix, then re-run:
  $hint"
fi
say "  user namespaces: ok"

# ── 3. the agent image, pinned to the ref this script came from ──────────────
step "Agent image"
image="${QUASAR_AGENT_IMAGE:-}"
image_from="${image:+QUASAR_AGENT_IMAGE}"
if [ -z "$image" ]; then
  image_from="no QUASAR_REF or QUASAR_AGENT_IMAGE given"
  ref="${QUASAR_REF:-}"
  case "$ref" in
    "") ;;
    v[0-9]*.[0-9]*.[0-9]*) image="$IMAGE_REPO:${ref#v}"; image_from="release $ref" ;;
    *)
      if printf '%s' "$ref" | grep -Eq '^[0-9a-f]{40}$'; then
        image="$IMAGE_REPO:sha-$(printf '%.7s' "$ref")"; image_from="commit $(printf '%.7s' "$ref")"
      else
        image="$IMAGE_REPO:$(printf '%s' "$ref" | tr '/' '-')"; image_from="branch $ref"
      fi ;;
  esac
fi

if [ "$DRY" = 1 ]; then
  say "  would use: ${image:-$LOCAL_IMAGE (local build, if present)} ($image_from)"
else
  if [ -n "$image" ] && $SUDO docker pull "$image" >/dev/null 2>&1; then
    say "  pulled $image (from $image_from)"
  elif $SUDO docker image inspect "$LOCAL_IMAGE" >/dev/null 2>&1; then
    [ -n "$image" ] && say "  WARN: could not pull $image (from $image_from)"
    say "  using the local build $LOCAL_IMAGE already on this host"
    image="$LOCAL_IMAGE"
  else
    host_error "no agent image: ${image:+could not pull $image (from $image_from), and }$LOCAL_IMAGE is not on this host. For a release, re-run with QUASAR_REF=<the release tag> or QUASAR_AGENT_IMAGE=<digest reference from the release body>; for a source build, build $LOCAL_IMAGE here with deploy/build-images.sh first."
  fi
fi
[ -n "$image" ] || image="$LOCAL_IMAGE"

# ── 4. files ─────────────────────────────────────────────────────────────────
node_name="${NODE_NAME:-$(hostname -s 2>/dev/null || hostname)}"
home_root="${QUASAR_HOME_ROOT:-/var/lib/quasar/homes}"
render_node="${QUASAR_RENDER_NODE:-$render_node}"
compose_files="docker-compose.yml"
[ "$gpu" = nvidia ] && compose_files="docker-compose.yml:docker-compose.nvidia.yml"

step "Install"
say "  directory:   $DIR"
say "  node name:   $node_name"
say "  home root:   $home_root"
say "  render node: $render_node"
say "  compose:     $compose_files"

if [ "$DRY" = 1 ]; then
  say ""
  say "dry run: nothing written, nothing started."
  exit 0
fi

$SUDO install -d -m 0755 "$DIR" "$home_root"
compose_yaml | $SUDO tee "$DIR/docker-compose.yml" >/dev/null
if [ "$gpu" = nvidia ]; then
  nvidia_yaml | $SUDO tee "$DIR/docker-compose.nvidia.yml" >/dev/null
else
  $SUDO rm -f "$DIR/docker-compose.nvidia.yml"
fi

# The .env is the ONLY place the enrollment string lands, and it is written by
# this shell (printf is a builtin: nothing below puts the token in an argv).
# Re-runs keep every operator-added line and replace only the managed keys.
managed='^(QUASAR_ENROLLMENT|NODE_NAME|QUASAR_AGENT_IMAGE|QUASAR_HOME_ROOT|QUASAR_RENDER_NODE|COMPOSE_FILE|COMPOSE_PROJECT_NAME)='
umask 077
env_tmp="$(mktemp)"
trap 'rm -f "$env_tmp"' EXIT
if $SUDO test -f "$DIR/.env"; then
  $SUDO cat "$DIR/.env" | grep -Ev "$managed" > "$env_tmp" || true
  say "  updating existing $DIR/.env (operator lines kept)"
else
  printf '# Written by deploy/enroll-host.sh. Add agent knobs (docs/configuration.md) below.\n' > "$env_tmp"
fi
{
  printf 'COMPOSE_PROJECT_NAME=%s\n' "$PROJECT"
  printf 'COMPOSE_FILE=%s\n' "$compose_files"
  printf 'NODE_NAME=%s\n' "$node_name"
  printf 'QUASAR_AGENT_IMAGE=%s\n' "$image"
  printf 'QUASAR_HOME_ROOT=%s\n' "$home_root"
  printf 'QUASAR_RENDER_NODE=%s\n' "$render_node"
  printf 'QUASAR_ENROLLMENT=%s\n' "$blob"
} >> "$env_tmp"
$SUDO install -m 0600 "$env_tmp" "$DIR/.env"
rm -f "$env_tmp"
say "  wrote $DIR/docker-compose.yml${gpu:+ }$( [ "$gpu" = nvidia ] && printf '+ docker-compose.nvidia.yml ')and .env (0600)"

# ── 5. start (or update) the one agent ───────────────────────────────────────
step "Starting the node agent"
# RFC 3339 with the Z: without it docker parses the stamp in the daemon's local
# zone and `logs --since` reaches back into a previous run's lines.
started_at="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
compose() {
  # shellcheck disable=SC2086
  $SUDO docker compose --project-directory "$DIR" --project-name "$PROJECT" \
    $(printf '%s' "$compose_files" | tr ':' '\n' | sed "s#^#-f $DIR/#" | tr '\n' ' ') "$@"
}
compose up -d quasar-node-agent
say "  started (compose project '$PROJECT'; re-running this script updates it in place)"

# ── 6. wait for enrollment ───────────────────────────────────────────────────
step "Waiting for enrollment (up to ${TAIL_SECS}s)"
elapsed=0
verdict=""
while :; do
  logs="$(compose logs --no-log-prefix --since "$started_at" quasar-node-agent 2>/dev/null || true)"
  if printf '%s' "$logs" | grep -q 'enrolled as host'; then
    verdict=enrolled; break
  elif printf '%s' "$logs" | grep -q 'reconnected as host'; then
    verdict=reconnected; break
  elif printf '%s' "$logs" | grep -q 'auth_failed'; then
    verdict=auth_failed; break
  elif printf '%s' "$logs" | grep -q 'cp-tls-pin-mismatch'; then
    verdict=pin_mismatch; break
  elif printf '%s' "$logs" | grep -q 'boot-enrollment-unconfigured'; then
    verdict=unconfigured; break
  elif printf '%s' "$logs" | grep -q 'CONTROL_PLANE_URL is required'; then
    # An agent that never learned QUASAR_ENROLLMENT: the local image predates #12.
    verdict=stale_image; break
  fi
  state="$(compose ps --format '{{.State}}' quasar-node-agent 2>/dev/null || true)"
  case "$state" in exited*|dead*) verdict=exited; break ;; esac
  [ "$elapsed" -lt "$TAIL_SECS" ] || { verdict=timeout; break; }
  sleep 2; elapsed=$((elapsed + 2))
done

case "$verdict" in
  enrolled)
    say "  enrolled: this host is now '$node_name' in Admin → Fleet."
    say ""
    say "Firewall was not touched. If sessions launch but video never arrives, the"
    say "host's readiness in Admin → Fleet names the UDP range and the exact rule."
    exit 0 ;;
  reconnected)
    say "  already enrolled: the agent reconnected as '$node_name' with its saved node secret."
    exit 0 ;;
  auth_failed)
    host_error "the control plane refused the credential (auth_failed). The token was expired, already used, minted for a different node name, or '$node_name' already has a live agent. Mint a fresh string in Admin → Fleet → Enroll host and re-run." ;;
  pin_mismatch)
    host_error "the certificate the control plane presented does not match the pin in the enrollment string (cp-tls-pin-mismatch). Mint a fresh string from the control plane's own page, or set CONTROL_PLANE_FINGERPRINT in $DIR/.env to the fingerprint= line from its startup log." ;;
  unconfigured)
    host_error "the agent started without an enrollment (boot-enrollment-unconfigured) — $DIR/.env did not reach it. Check 'docker compose --project-directory $DIR config'." ;;
  stale_image)
    host_error "the agent image on this host ($image) predates the enrollment string: it asks for CONTROL_PLANE_URL instead of reading QUASAR_ENROLLMENT. Give it a current image — QUASAR_AGENT_IMAGE=<published reference>, or build/copy quasar-node-agent:latest from the control plane's tree — then re-run this command." ;;
  exited)
    host_error "the agent container exited. Its log: docker compose --project-directory $DIR logs quasar-node-agent" ;;
  *)
    printf 'enroll-host: not enrolled after %ss — still connecting. Watch it with:\n  docker compose --project-directory %s logs -f quasar-node-agent\n' "$TAIL_SECS" "$DIR" >&2
    exit 3 ;;
esac
