#!/usr/bin/env python3
"""Build docs/reports/2026-08-28-ui-v3/report.html from the input files next to it.

Stdlib only. Re-run any time; it always regenerates the whole file.

Inputs (all under the report directory, next to this script's target):
  overview.md      prose for the Summary section (what shipped, how to log in)
  screens.json      list of surfaces: {section, route, title, mock, impl, notes, mock_note}
  deviations.md    one markdown table (spec section 9 seed + task-32 additions)
  backend.md       prose/table for Backend changes
  evidence/*.txt   one file per test/build gate; tailed into Test evidence, sorted by filename
  copy-pass.md     prose for Copy pass notes
  followups.md     prose for Follow-ups

Commit list is generated by running `git log --oneline origin/develop..HEAD` in the repo root;
if that fails (detached worktree, no origin, etc.) the report says so instead of guessing.

Usage:
  python3 scripts/ui-v3/build-report.py

Screenshots referenced by screens.json are embedded as base64 data URIs so report.html stands
alone when copied elsewhere; missing files render a visible "not captured" placeholder instead of
breaking the build.
"""
import base64
import html
import json
import re
import subprocess
import sys
from pathlib import Path

SCRIPT = Path(__file__).resolve()
REPO_ROOT = SCRIPT.parents[2]
REPORT_DIR = REPO_ROOT / "docs" / "reports" / "2026-08-28-ui-v3"
EVIDENCE_DIR = REPORT_DIR / "evidence"
OUT_PATH = REPORT_DIR / "report.html"
# --linked writes report-linked.html with <img src="shots/..."> instead of data URIs:
# a few hundred kB next to its screenshots, for reading from this checkout.
INLINE = "--linked" not in sys.argv
if not INLINE:
    OUT_PATH = REPORT_DIR / "report-linked.html"
EVIDENCE_TAIL_LINES = 200

MIME_BY_EXT = {
    "png": "image/png",
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "gif": "image/gif",
    "webp": "image/webp",
    "svg": "image/svg+xml",
}


def esc(s):
    return html.escape(s or "", quote=True)


def render_inline(text):
    text = esc(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    return text


def split_table_row(line):
    """Split one markdown table row into cells, honouring `\\|` as a literal pipe
    (needed for cells that contain code like `state=active\\|ended\\|failed\\|all`).
    Strips one leading/trailing empty cell from the line's own leading/trailing `|`.
    """
    cells = []
    current = []
    i = 0
    s = line.strip()
    while i < len(s):
        ch = s[i]
        if ch == "\\" and i + 1 < len(s) and s[i + 1] == "|":
            current.append("|")
            i += 2
            continue
        if ch == "|":
            cells.append("".join(current))
            current = []
            i += 1
            continue
        current.append(ch)
        i += 1
    cells.append("".join(current))
    if cells and cells[0].strip() == "":
        cells = cells[1:]
    if cells and cells[-1].strip() == "":
        cells = cells[:-1]
    return [c.strip() for c in cells]


def render_table(lines):
    """lines: raw markdown table row strings (header, separator, body rows...)."""
    if len(lines) < 2:
        return ""
    rows = [split_table_row(line) for line in lines]
    header = rows[0]
    body = rows[2:]  # rows[1] is the --- separator
    out = ['<table class="dtable"><thead><tr>']
    for h in header:
        out.append(f"<th>{render_inline(h)}</th>")
    out.append("</tr></thead><tbody>")
    for r in body:
        out.append("<tr>")
        for i, c in enumerate(r):
            cls = ' class="src-col"' if header and header[-1].lower() == "source" and i == len(r) - 1 else ""
            out.append(f"<td{cls}>{render_inline(c)}</td>")
        out.append("</tr>")
    out.append("</tbody></table>")
    return "\n".join(out)


def render_markdown(text):
    """Minimal markdown -> HTML: headers, paragraphs, lists, fenced code, pipe tables, **b**, `code`."""
    lines = text.split("\n")
    out = []
    i = 0
    in_code = False
    code_lines = []
    list_open = False
    table_lines = []

    def flush_list():
        nonlocal list_open
        if list_open:
            out.append("</ul>")
            list_open = False

    def flush_table():
        nonlocal table_lines
        if table_lines:
            out.append(render_table(table_lines))
            table_lines = []

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if stripped.startswith("```"):
            if not in_code:
                flush_list()
                flush_table()
                in_code = True
                code_lines = []
            else:
                out.append(f"<pre><code>{esc(chr(10).join(code_lines))}</code></pre>")
                in_code = False
            i += 1
            continue
        if in_code:
            code_lines.append(line)
            i += 1
            continue
        if stripped.startswith("<!--"):
            i += 1
            continue
        if stripped.startswith("#"):
            flush_list()
            flush_table()
            level = min(len(stripped) - len(stripped.lstrip("#")), 5)
            content = stripped[level:].strip()
            out.append(f"<h{level + 2}>{render_inline(content)}</h{level + 2}>")
            i += 1
            continue
        if stripped.startswith("|"):
            flush_list()
            table_lines.append(stripped)
            i += 1
            continue
        flush_table()
        if stripped.startswith("- "):
            if not list_open:
                out.append("<ul>")
                list_open = True
            out.append(f"<li>{render_inline(stripped[2:])}</li>")
            i += 1
            continue
        flush_list()
        if stripped == "":
            i += 1
            continue
        para = [stripped]
        i += 1
        while i < len(lines) and lines[i].strip() != "" and not lines[i].strip().startswith(("#", "```", "|", "- ")):
            para.append(lines[i].strip())
            i += 1
        out.append(f"<p>{render_inline(' '.join(para))}</p>")

    flush_list()
    flush_table()
    return "\n".join(out)


def parse_table_rows(text):
    """Raw table row lines from a markdown file (comments and non-table lines dropped)."""
    rows = []
    for line in text.split("\n"):
        s = line.strip()
        if s.startswith("<!--"):
            continue
        if s.startswith("|"):
            rows.append(s)
    return rows


def read(path, default=""):
    p = REPORT_DIR / path
    if not p.exists():
        return default
    return p.read_text()


def img_tag(rel_path, alt, extra_class=""):
    if not rel_path:
        return (
            f'<div class="shot-missing {esc(extra_class)}">no mock for this surface'
            f'<span class="path">compare with the implementation only</span></div>'
        )
    abs_path = (REPORT_DIR / rel_path).resolve()
    if not abs_path.exists():
        return (
            f'<div class="shot-missing {esc(extra_class)}">not captured'
            f'<span class="path">{esc(rel_path)}</span></div>'
        )
    if not INLINE:
        return (
            f'<img class="shot {esc(extra_class)}" loading="lazy" '
            f'src="{esc(rel_path)}" data-original="{esc(rel_path)}" '
            f'alt="{esc(alt)}" onclick="lightbox(this)">'
        )
    data = abs_path.read_bytes()
    b64 = base64.b64encode(data).decode("ascii")
    ext = abs_path.suffix.lstrip(".").lower()
    mime = MIME_BY_EXT.get(ext, "application/octet-stream")
    return (
        f'<img class="shot {esc(extra_class)}" loading="lazy" '
        f'src="data:{mime};base64,{b64}" data-original="{esc(rel_path)}" '
        f'alt="{esc(alt)}" onclick="lightbox(this)">'
    )


def build_screens_html(screens):
    groups = []
    seen = {}
    for s in screens:
        sec = s.get("section", "Other")
        if sec not in seen:
            seen[sec] = []
            groups.append(sec)
        seen[sec].append(s)

    out = []
    for sec in groups:
        out.append(f'<h3 class="screen-section">{esc(sec)}</h3>')
        for s in seen[sec]:
            out.append('<div class="screen-card">')
            out.append(
                f'<div class="screen-meta"><span class="route">{esc(s.get("route", ""))}</span>'
                f' <span class="dash">&middot;</span> <span class="title">{esc(s.get("title", ""))}</span></div>'
            )
            if s.get("notes"):
                out.append(f'<p class="notes">{render_inline(s["notes"])}</p>')
            if s.get("mock_note"):
                out.append(f'<p class="mock-note">{render_inline(s["mock_note"])}</p>')
            out.append('<div class="pair">')
            out.append(
                '<div class="pane"><div class="pane-label">Mock</div>'
                + img_tag(s.get("mock", ""), s.get("title", "") + ", mock")
                + "</div>"
            )
            out.append(
                '<div class="pane"><div class="pane-label">Implementation</div>'
                + img_tag(s.get("impl", ""), s.get("title", "") + ", implementation")
                + "</div>"
            )
            out.append("</div></div>")
    return "\n".join(out)


def build_evidence_html():
    if not EVIDENCE_DIR.exists():
        return '<p class="missing">No evidence directory found.</p>'
    files = sorted(p for p in EVIDENCE_DIR.glob("*.txt"))
    if not files:
        return '<p class="missing">No test evidence captured yet. Drop gate tails as .txt files in evidence/.</p>'
    parts = []
    for f in files:
        content = f.read_text(errors="replace")
        lines = content.splitlines()
        note = ""
        if len(lines) > EVIDENCE_TAIL_LINES:
            note = f'<p class="tail-note">Showing last {EVIDENCE_TAIL_LINES} of {len(lines)} lines.</p>'
            content = "\n".join(lines[-EVIDENCE_TAIL_LINES:])
        name = f.stem.replace("-", " ").replace("_", " ")
        parts.append(f"<h3>{esc(name)}</h3>{note}<pre>{esc(content)}</pre>")
    return "\n".join(parts)


def build_commit_list_html():
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", "origin/develop..HEAD"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=20,
        )
    except Exception as e:  # noqa: BLE001 — surfaced in the report, not raised
        return f'<p class="missing">Could not run git ({esc(str(e))}). Paste <code>git log --oneline origin/develop..HEAD</code> here.</p>'
    if result.returncode == 0 and result.stdout.strip():
        return f"<pre>{esc(result.stdout.strip())}</pre>"
    err = result.stderr.strip() or "no output"
    return (
        f'<p class="missing">git log returned no commits ({esc(err)}). '
        f"Paste <code>git log --oneline origin/develop..HEAD</code> here once the branch has commits ahead of develop.</p>"
    )


CSS = """
:root{
  color-scheme: dark;
  --bg:#0b0c10; --panel:#14161c; --raised:#1b1e26; --line:#2a2e38;
  --text:#e6e8ee; --text-2:#a9adba; --text-3:#7d8291;
  --accent:#8b7bff; --accent-2:#6f5fe0;
  --ok:#4fbf7a; --warn:#e0b34f; --err:#e0604f;
  --mono: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  --sans: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
}
*{box-sizing:border-box}
html,body{margin:0;padding:0;background:var(--bg);color:var(--text);font-family:var(--sans);line-height:1.5}
body{padding:0 0 80px}
a{color:var(--accent)}
header.top{padding:32px clamp(16px,4vw,64px) 24px;border-bottom:1px solid var(--line);position:sticky;top:0;background:rgba(11,12,16,.92);backdrop-filter:blur(6px);z-index:5}
header.top h1{margin:0 0 6px;font-size:22px;letter-spacing:.02em}
header.top .sub{color:var(--text-3);font-size:13px}
nav.toc{display:flex;flex-wrap:wrap;gap:6px 14px;margin-top:14px}
nav.toc a{color:var(--text-2);font-size:13px;text-decoration:none;padding:4px 0;border-bottom:1px solid transparent}
nav.toc a:hover{color:var(--text);border-color:var(--accent)}
main{padding:0 clamp(16px,4vw,64px);max-width:1400px;margin:0 auto}
section{padding:40px 0;border-bottom:1px solid var(--line)}
section:last-child{border-bottom:none}
section h2{font-size:19px;margin:0 0 18px;display:flex;align-items:center;gap:10px}
section h2 .n{color:var(--text-3);font-family:var(--mono);font-size:13px}
h3{font-size:15px;color:var(--text);margin:22px 0 10px}
h3.screen-section{margin-top:34px;padding-top:14px;border-top:1px dashed var(--line);text-transform:uppercase;letter-spacing:.06em;font-size:12px;color:var(--text-3)}
h4,h5{font-size:13px;color:var(--text-2)}
p{color:var(--text-2);margin:8px 0}
p.missing{color:var(--warn);font-style:italic}
p.tail-note{color:var(--text-3);font-size:12px;font-style:italic;margin-top:-4px}
code{font-family:var(--mono);background:var(--raised);padding:1px 5px;border-radius:4px;font-size:.92em}
pre{font-family:var(--mono);background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:14px 16px;overflow:auto;font-size:12.5px;color:var(--text-2);white-space:pre-wrap;word-break:break-word}
ul{color:var(--text-2);padding-left:22px}
li{margin:4px 0}
table.dtable{width:100%;border-collapse:collapse;margin:10px 0 20px;font-size:13px}
table.dtable th,table.dtable td{border:1px solid var(--line);padding:8px 10px;text-align:left;vertical-align:top}
table.dtable th{background:var(--panel);color:var(--text);font-weight:600}
table.dtable td{color:var(--text-2)}
table.dtable td.src-col{color:var(--text-3);font-family:var(--mono);font-size:11.5px;white-space:nowrap}
.screen-card{border:1px solid var(--line);border-radius:10px;padding:16px;margin:14px 0;background:var(--panel)}
.screen-meta{font-family:var(--mono);font-size:12.5px;color:var(--text-3);margin-bottom:6px}
.screen-meta .route{color:var(--accent)}
.screen-meta .title{color:var(--text)}
.screen-meta .dash{opacity:.5}
.notes{margin:4px 0}
.mock-note{color:var(--text-3);font-size:12px;font-style:italic}
.pair{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:10px}
.pane{min-width:0}
.pane-label{font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:var(--text-3);margin-bottom:6px}
img.shot{max-width:100%;max-height:360px;border-radius:6px;border:1px solid var(--line);cursor:zoom-in;display:block;background:var(--raised)}
.shot-missing{border:1px dashed var(--line);border-radius:6px;padding:22px 12px;color:var(--text-3);text-align:center;font-size:13px;background:var(--raised)}
.shot-missing .path{display:block;font-family:var(--mono);font-size:11px;margin-top:6px;color:var(--text-3);word-break:break-all}
#lightbox{position:fixed;inset:0;background:rgba(0,0,0,.86);display:none;align-items:center;justify-content:center;z-index:50;cursor:zoom-out;padding:30px}
#lightbox.open{display:flex}
#lightbox img{max-width:95vw;max-height:95vh;border-radius:6px;box-shadow:0 10px 40px rgba(0,0,0,.6)}
footer{padding:30px clamp(16px,4vw,64px);color:var(--text-3);font-size:12px}
@media (max-width: 900px){.pair{grid-template-columns:1fr}}
"""

JS = """
function lightbox(imgEl){
  var lb = document.getElementById('lightbox');
  var img = document.getElementById('lightbox-img');
  img.src = imgEl.src;
  lb.classList.add('open');
}
document.addEventListener('DOMContentLoaded', function(){
  var lb = document.getElementById('lightbox');
  lb.addEventListener('click', function(){ lb.classList.remove('open'); });
});
"""


def main():
    REPORT_DIR.mkdir(parents=True, exist_ok=True)

    overview_html = render_markdown(read("overview.md", "_No overview.md found._"))
    backend_html = render_markdown(read("backend.md", "_No backend.md found._"))
    followups_html = render_markdown(read("followups.md", "_No followups.md found._"))
    copy_pass_html = render_markdown(read("copy-pass.md", "_No copy-pass.md found._"))

    deviations_text = read("deviations.md", "")
    deviations_rows = parse_table_rows(deviations_text)
    deviations_html = render_table(deviations_rows) if deviations_rows else '<p class="missing">No deviations.md table found.</p>'

    screens_path = REPORT_DIR / "screens.json"
    if screens_path.exists():
        screens = json.loads(screens_path.read_text())
    else:
        screens = []
    screens_html = build_screens_html(screens) if screens else '<p class="missing">No screens.json found.</p>'

    evidence_html = build_evidence_html()
    commits_html = build_commit_list_html()

    captured = sum(1 for s in screens if (REPORT_DIR / s.get("impl", "")).exists()) if screens else 0
    total = len(screens)

    doc = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Quasar UI v3 completion report</title>
<style>{CSS}</style>
</head>
<body>
<header class="top">
  <h1>Quasar UI v3 completion report</h1>
  <div class="sub">Generated by scripts/ui-v3/build-report.py &middot; branch feat/ui-v3 &middot; {esc(str(captured))}/{esc(str(total))} screens captured</div>
  <nav class="toc">
    <a href="#summary">Summary</a>
    <a href="#screens">Screens</a>
    <a href="#deviations">Deviations</a>
    <a href="#backend">Backend changes</a>
    <a href="#evidence">Test evidence</a>
    <a href="#copy-pass">Copy pass</a>
    <a href="#followups">Follow-ups</a>
    <a href="#commits">Commits</a>
  </nav>
</header>
<main>

<section id="summary">
  <h2>Summary <span class="n">what shipped, how to log in</span></h2>
  {overview_html}
</section>

<section id="screens">
  <h2>Screens <span class="n">mock left, implementation right</span></h2>
  {screens_html}
</section>

<section id="deviations">
  <h2>Deviations from the design, and why</h2>
  {deviations_html}
</section>

<section id="backend">
  <h2>Backend changes</h2>
  {backend_html}
</section>

<section id="evidence">
  <h2>Test evidence</h2>
  {evidence_html}
</section>

<section id="copy-pass">
  <h2>Copy pass notes</h2>
  {copy_pass_html}
</section>

<section id="followups">
  <h2>Follow-ups</h2>
  {followups_html}
</section>

<section id="commits">
  <h2>Commit list <span class="n">git log --oneline origin/develop..HEAD</span></h2>
  {commits_html}
</section>

</main>
<footer>docs/reports/2026-08-28-ui-v3/report.html &middot; rebuild with <code>python3 scripts/ui-v3/build-report.py</code></footer>
<div id="lightbox"><img id="lightbox-img" src="" alt=""></div>
<script>{JS}</script>
</body>
</html>
"""

    OUT_PATH.write_text(doc)
    print(f"wrote {OUT_PATH} ({len(doc)} bytes); screens {captured}/{total} captured")


if __name__ == "__main__":
    main()
