package main

import (
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"

	"github.com/accreleus/quasar/control-plane/internal/telemetry"
	"gopkg.in/yaml.v3"
)

// TestMetricsManifestDrift is the second half of the guarantee TestOpenAPIDrift
// gives for routes: the two places that describe a metric KEY must agree.
// `protocol/openapi.yaml`'s AgentMetrics/BrowserMetrics say what shape a sample
// may have; `docs/session-trace/metrics.json` says what each key MEANS. Before
// this, a key could be declared in one and absent from the other indefinitely,
// which is how `freeze_count` came to be stored, taxonomised and undocumented.
//
// Direction 1 (strict): every property in the OpenAPI schema must exist in the
// manifest, unless it is in the reviewed no-producer list below.
// Direction 2 (strict): every manifest key for that source must be declared in
// the OpenAPI schema.
func TestMetricsManifestDrift(t *testing.T) {
	schemas := openAPIMetricSchemas(t)

	// Documented shapes with NO producer. Each entry is a finding, not a
	// convenience: the key is declared on the wire and nothing has ever sent it.
	// Removing a property is a subtractive contract change, so they stay
	// declared and stay named here instead of being quietly tolerated.
	noProducer := map[string]string{
		"AgentMetrics.overlay_frames": "the host-side overlay was removed in #270; nothing counts frames",
	}

	for _, tc := range []struct {
		schema string
		source string
	}{
		{"AgentMetrics", "agent"},
		{"BrowserMetrics", "browser"},
	} {
		props := schemas[tc.schema]
		if len(props) == 0 {
			t.Fatalf("openapi.yaml has no %s properties", tc.schema)
		}
		// known: every key the manifest describes for this source — what a
		// declared property is allowed to be.
		// expected: the STORED subset — what the schema MUST declare. A key the
		// ingest path drops may be declared (BrowserMetrics doubles as the POST
		// /stats request body, and a posted-then-dropped key is part of that
		// shape) but is not required to be.
		known := map[string]bool{}
		expected := map[string]bool{}
		for _, e := range telemetry.Manifest().Metrics {
			if e.Source != tc.source {
				continue
			}
			known[e.Key] = true
			if e.IsStored() {
				expected[e.Key] = true
			}
		}

		var missingFromManifest, missingFromSpec []string
		for p := range props {
			if known[p] {
				continue
			}
			if _, ok := noProducer[tc.schema+"."+p]; ok {
				continue
			}
			missingFromManifest = append(missingFromManifest, p)
		}
		for k := range expected {
			if !props[k] {
				missingFromSpec = append(missingFromSpec, k)
			}
		}
		sort.Strings(missingFromManifest)
		sort.Strings(missingFromSpec)

		if len(missingFromManifest) > 0 {
			t.Errorf("%s: %d key(s) in protocol/openapi.yaml but NOT in docs/session-trace/metrics.json:\n  %s",
				tc.schema, len(missingFromManifest), strings.Join(missingFromManifest, "\n  "))
		}
		if len(missingFromSpec) > 0 {
			t.Errorf("%s: %d stored key(s) in docs/session-trace/metrics.json but NOT declared in protocol/openapi.yaml:\n  %s",
				tc.schema, len(missingFromSpec), strings.Join(missingFromSpec, "\n  "))
		}
	}
}

// openAPIMetricSchemas returns {schemaName: {propertyName: true}} for the two
// metric schemas.
func openAPIMetricSchemas(t *testing.T) map[string]map[string]bool {
	t.Helper()
	data, err := os.ReadFile(openAPIPath(t))
	if err != nil {
		t.Fatalf("read openapi.yaml: %v", err)
	}
	var doc struct {
		Components struct {
			Schemas map[string]struct {
				Properties map[string]yaml.Node `yaml:"properties"`
			} `yaml:"schemas"`
		} `yaml:"components"`
	}
	if err := yaml.Unmarshal(data, &doc); err != nil {
		t.Fatalf("parse openapi.yaml: %v", err)
	}
	out := map[string]map[string]bool{}
	for _, name := range []string{"AgentMetrics", "BrowserMetrics"} {
		props := map[string]bool{}
		for p := range doc.Components.Schemas[name].Properties {
			props[p] = true
		}
		out[name] = props
	}
	return out
}

// The web bundle's copy of the manifest is generated by the same sync target as
// the Go one. Checked here rather than in vitest as well so a Go-only run still
// catches a half-run sync.
func TestWebMetricsManifestIsInSync(t *testing.T) {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	root := filepath.Join(filepath.Dir(thisFile), "..", "..", "..")
	want, err := os.ReadFile(filepath.Join(root, "docs", "session-trace", "metrics.json"))
	if err != nil {
		t.Fatalf("read docs manifest: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(root, "web", "src", "lib", "metrics.generated.json"))
	if err != nil {
		t.Fatalf("read web manifest copy: %v", err)
	}
	if string(want) != string(got) {
		t.Fatal("web/src/lib/metrics.generated.json is stale. Run: make docs-metrics-sync")
	}
}
